import { GoogleGenAI, Type, Schema } from "@google/genai";

export interface PromptData {
  regular: string;
  html: string;
}

interface ImagePart {
    inlineData: {
      data: string;
      mimeType: string;
    };
}

const getAiClient = () => {
  const API_KEY = process.env.API_KEY;
  if (!API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
  }
  return new GoogleGenAI({ apiKey: API_KEY });
};

export const generatePromptFromImage = async (imagePart: ImagePart, aspectRatio: string = "1:1"): Promise<PromptData> => {
  const promptForGemini = `Analyze this image and generate two versions of a prompt:

1. "regular": A highly detailed and descriptive text prompt for an AI image generation model (like Midjourney/DALL-E). Focus on style, composition, lighting, and mood.

2. "html": A structured code representation of the image content.
   - CASE A: If the image is a PHOTOGRAPH, ART, PERSON, or SCENE: Generate a detailed JSON object (formatted as a pretty-printed string with indentation) describing the image. You MUST use these specific keys: "scene_description", "subject" (object with details like type, age, hair, features, attire, position), "action", "environment" (setting, elements), "lighting" (type, color), "style" (aesthetic, medium). The output must look like a code block.
   - CASE B: If the image is a WEBSITE, UI, or LAYOUT: Provide the semantic HTML structure (and CSS/Tailwind classes if applicable) to reproduce the design.

The target aspect ratio is ${aspectRatio}.

Return a JSON object with keys "regular" and "html".`;

  const schema: Schema = {
    type: Type.OBJECT,
    properties: {
      regular: { type: Type.STRING, description: "The detailed text prompt." },
      html: { type: Type.STRING, description: "The structured code representation (JSON or HTML)." },
    },
    required: ["regular", "html"],
  };

  try {
    const ai = getAiClient();
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: {
        parts: [
          { text: promptForGemini },
          imagePart
        ]
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: schema,
      }
    });
    
    if (response.text) {
        return JSON.parse(response.text) as PromptData;
    } else {
        throw new Error('No text was generated by the model.');
    }
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    if (error instanceof Error) {
        throw new Error(`Gemini API Error: ${error.message}`);
    }
    throw new Error("An unknown error occurred while communicating with the Gemini API.");
  }
};

export const refinePromptWithGemini = async (currentPrompts: PromptData, instruction: string): Promise<PromptData> => {
  const ai = getAiClient();
  const systemInstruction = `You are an expert AI prompt engineer. Your task is to modify the provided prompts based strictly on the user's instruction.
  
  You must update BOTH the "regular" and "html" versions of the prompt.
  
  IMPORTANT for the "html" field:
  - If the current "html" content is a JSON string (describing a scene/subject), keep it as valid JSON. Update the values inside the JSON structure to reflect the changes. Ensure it is pretty-printed (indented).
  - If the current "html" content is HTML code (for a UI/Website), keep it as HTML code and update the structure/styles.
  - Ensure the output "html" string is formatted like code (indentation).

  Return a JSON object with "regular" and "html" keys.`;

  const contents = `
Current Regular Prompt:
${currentPrompts.regular}

Current HTML/Code Prompt:
${currentPrompts.html}

User Instruction:
${instruction}
`;

  const schema: Schema = {
    type: Type.OBJECT,
    properties: {
      regular: { type: Type.STRING },
      html: { type: Type.STRING },
    },
    required: ["regular", "html"],
  };

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      config: { 
          systemInstruction,
          responseMimeType: "application/json",
          responseSchema: schema
      },
      contents: contents,
    });

    if (response.text) {
      return JSON.parse(response.text) as PromptData;
    } else {
      throw new Error('No text was generated.');
    }
  } catch (error) {
    console.error("Error refining prompt:", error);
    if (error instanceof Error) {
      throw new Error(`Refine Error: ${error.message}`);
    }
    throw new Error("An unknown error occurred while refining the prompt.");
  }
};