import React from 'react';

interface GeneratedImageProps {
  imageUrl: string | null;
  isLoading: boolean;
  onDownload: () => void;
}

const GeneratedImage: React.FC<GeneratedImageProps> = ({ imageUrl, isLoading, onDownload }) => {
  if (!imageUrl && !isLoading) return null;

  return (
    <div className="mt-6 bg-brand-gray rounded-xl p-4 shadow-lg border border-brand-surface">
      <h3 className="text-lg font-semibold text-gray-200 mb-4">Generated Image</h3>
      
      <div className="relative w-full min-h-[300px] bg-brand-dark rounded-lg flex items-center justify-center overflow-hidden border border-brand-surface">
        {isLoading ? (
          <div className="flex flex-col items-center space-y-3">
             <svg className="animate-spin h-10 w-10 text-brand-primary" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <p className="text-gray-400 text-sm animate-pulse">Creating your masterpiece...</p>
          </div>
        ) : imageUrl ? (
          <img src={imageUrl} alt="Generated by Gemini" className="w-full h-auto object-contain rounded-md" />
        ) : null}
      </div>

      {imageUrl && !isLoading && (
        <div className="mt-4 flex justify-end">
          <button
            onClick={onDownload}
            className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-full shadow-sm text-brand-dark bg-brand-primary hover:brightness-110 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-primary transition-all"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download
          </button>
        </div>
      )}
    </div>
  );
};

export default GeneratedImage;